import json
import numpy as np

# Import the specific scorers from the pycocoevalcap library
from pycocoevalcap.bleu.bleu import Bleu
from pycocoevalcap.rouge.rouge import Rouge
# from pycocoevalcap.meteor.meteor import Meteor
from pycocoevalcap.cider.cider import Cider

class NLPEvaluator:
    def __init__(self):
        """
        Initializes the scorers.
        Note: Meteor requires Java to be installed on the system path.
        """
        try:
            self.cider_scorer = Cider()
            # self.meteor_scorer = Meteor()
            self.rouge_scorer = Rouge()
            # Bleu(4) computes BLEU-1, BLEU-2, BLEU-3, and BLEU-4
            self.bleu_scorer = Bleu(4)
        except Exception as e:
            print("Error initializing scorers. Did you install Java (for METEOR)?")
            print(f"Details: {e}")
            exit(1)

    def calculate_scores(self, references_dict, generated_dict):
        """
        Calculates metrics for generated sentences against references.

        Args:
            references_dict (dict): Map of ID -> list of reference strings.
                                    E.g., {'img1': ['go west', 'walk left']}
            generated_dict (dict): Map of ID -> list containing ONE generated string.
                                    E.g., {'img1': ['go west past the tree']}
        Returns:
            dict: A dictionary mapping metric names to their average scores.
        """
        scores = {}

        # --- 1. CIDEr ---
        # CIDEr is corpus-based, so it needs all data at once to calculate TF-IDF.
        cider_score, _ = self.cider_scorer.compute_score(references_dict, generated_dict)
        scores['CIDEr'] = cider_score

        # --- 2. METEOR ---
        # meteor_score, _ = self.meteor_scorer.compute_score(references_dict, generated_dict)
        # scores['METEOR'] = meteor_score

        # --- 3. ROUGE-L ---
        rouge_score, _ = self.rouge_scorer.compute_score(references_dict, generated_dict)
        scores['ROUGE_L'] = rouge_score

        # --- 4. BLEU (1-4) ---
        # Bleu returns a list of scores [B1, B2, B3, B4]
        bleu_scores, _ = self.bleu_scorer.compute_score(references_dict, generated_dict)
        for i, score in enumerate(bleu_scores):
            scores[f'BLEU-{i+1}'] = score

        return scores

# =========================================
# Main Execution Example
# =========================================
if __name__ == "__main__":
    # Define sample data based on the figure shown previously.
    # COCO eval tools expect dictionaries mapping a unique ID (key)
    # to a LIST of strings (value).

    # The unique ID for this navigation situation
    situation_id = "nav_instruction_001"

    # Ground Truth references (often there are multiple valid ways to say it)
    references = [
        "Go past the brick structure and head west",
    ]

    # The instruction generated by the AI agent
    # Note: It must be a list, even if it's just one generation.
    generated = [
        "Take a left after the red building"
    ]

    # Format data into dictionaries required by the scorer
    # gts = Ground Truths, res = Results (generated)
    gts_dict = {situation_id: references}
    res_dict = {situation_id: generated}

    print("="*60)
    print("NLP INSTRUCTION EVALUATION")
    print("="*60)
    print(f"References List:\n {json.dumps(references, indent=2)}")
    print("-" * 30)
    print(f"Generated:\n {json.dumps(generated, indent=2)}")
    print("="*60 + "\n")
    print("Calculating scores (this might take a moment, especially for METEOR)...")

    # Instantiate the evaluator class
    evaluator = NLPEvaluator()

    # Calculate scores
    final_scores = evaluator.calculate_scores(gts_dict, res_dict)

    # Print Results
    print("\nRESULTS:")
    print("-" * 30)
    for metric, score in final_scores.items():
        # Typical reporting format is percentage (score * 100) rounded to 1 or 2 decimals
        print(f"{metric:<10}: {score*100:.2f}")
    print("-" * 30)
